- name: install few packages
  hosts: all
  become: yes
  tasks:
  - name: install postfix
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - postfix
    - mysql
    - nginx  