- name: create ec2 and r53 records
  hosts: localhost
  vars:
    zone: daws78s-nnr.online
    instances:
    - db
    - backend
    - frontend
  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      name: "{{ item }}"
      security_group: ALLOW2 #replace with you AWS values
      image_id: ami-090252cbe067a9e58
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instances_info

  - name: print output
    ansible.builtin.debug: